# Generated by Django 3.0.7 on 2020-07-24 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metrica', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acompanhamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_medicao', models.DateField(verbose_name='Data de Medição')),
                ('medida', models.FloatField(verbose_name='Medida')),
                ('metrica', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='metrica.Metrica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.Usuario')),
            ],
        ),
    ]
