# Generated by Django 3.0.7 on 2020-07-26 23:57

from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0002_auto_20200726_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanhamento',
            name='dt_medicao',
            field=models.DateField(default=timezone.now().date(), verbose_name='Data de Medição'),
        ),
    ]
