# Generated by Django 3.0.7 on 2020-07-24 23:14

from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, validators=[usuario.models.verifica_se_usuario_ja_existe], verbose_name='Nome')),
            ],
        ),
    ]
