# Generated by Django 3.0.7 on 2020-07-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='altura',
            field=models.FloatField(blank=True, null=True, verbose_name='Altura'),
        ),
    ]
