# Generated by Django 3.0.7 on 2020-07-23 23:36

from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=50, validators=[usuario.models.verifica_se_usuario_ja_existe], verbose_name='Nome'),
        ),
    ]
