# Generated by Django 3.0.7 on 2020-07-25 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='digitos',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dígitos'),
        ),
    ]
