# Generated by Django 3.0.7 on 2020-07-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0002_auto_20200725_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='digitos',
            field=models.IntegerField(verbose_name='Dígitos'),
        ),
    ]
